services:
  nginx:
    image: ffmpeg_trac:latest
    pull_policy: never
    restart: unless-stopped
    volumes:
      - ./home:/home/trac
    networks:
      - front
      - back
    ports:
      - "${HTTP_PORT:-8080}:8080"
    depends_on:
      - trac
    command: nginx
  anubis:
    image: ghcr.io/techarohq/anubis:latest
    restart: unless-stopped
    networks:
      - back
      - front
    environment:
      - BIND=:8080
      - DIFFICULTY=5
      - TARGET=http://trac:3030
  trac:
    image: ffmpeg_trac:latest
    pull_policy: build
    build: trac
    restart: unless-stopped
    environment:
      - UWSGI_MASTER=true
      - UWSGI_LOG_MASTER=true
      - UWSGI_PROCESSES=${UWSGI_PROCESSES:-4}
      - UWSGI_THREADS=${UWSGI_THREADS:-4}
      - HTTP_X_FORWARDED_PROTO="${HTTP_PROTO:-http}"
    volumes:
      - ./home:/home/trac
    networks:
      - back
      - front
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: uwsgi
  update_git:
    image: ffmpeg_trac:latest
    pull_policy: never
    restart: unless-stopped
    volumes:
      - ./home:/home/trac
    environment:
      - GIT_REPO_URL=${GIT_REPO_URL:-https://git.videolan.org/git/ffmpeg.git}
      - GIT_REPO_NAME=${GIT_REPO_NAME:-ffmpeg}
    networks:
      - back
      - front
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: update_git
  ircbot:
    image: ffmpeg_trac:latest
    pull_policy: never
    restart: unless-stopped
    environment:
      - IRC_SERVER=${IRC_SERVER:-irc.libera.chat}
      - IRC_PORT=${IRC_SERVER:-+6697}
      - IRC_CHANNEL=${IRC_CHANNEL:-#testmybot}
      - IRC_NICK=${IRC_NICK:-FFTrac}
      - IRC_HTTP_HOST=0.0.0.0
      - IRC_HTTP_PORT=8787
    networks:
      - back
      - front
    command: ircbot
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme_via_.env}
      - POSTGRES_USER=${POSTGRES_USER:-trac}
      - POSTGRES_DB=${POSTGRES_DB:-trac}
      - PGDATA=/var/lib/postgresql/data/17
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - back

volumes:
  pgdata:

networks:
  front:
  back:
    internal: true
