services:
  nginx:
    image: ffmpeg_trac:latest
    restart: unless-stopped
    volumes:
      - ./home:/home/trac
    networks:
      - back
      - front
    ports:
      - 8080:8080
    depends_on:
      - uwsgi
    command: nginx
  uwsgi:
    image: ffmpeg_trac:latest
    build: trac
    restart: unless-stopped
    environment:
      - UWSGI_MASTER=true
      - UWSGI_PROCESSES=${UWSGI_PROCESSES:-4}
      - UWSGI_THREADS=${UWSGI_THREADS:-4}
    volumes:
      - ./home:/home/trac
    networks:
      - back
    command: uwsgi

volumes:
  mariadata:

networks:
  front:
  back:
    internal: true
