services:
  nginx:
    image: ffmpeg_trac:latest
    build: trac
    restart: unless-stopped
    volumes:
      - ./home:/home/trac
    networks:
      - back
      - front
    ports:
      - 8080:8080
    depends_on:
      - uwsgi
    command: nginx
  uwsgi:
    image: ffmpeg_trac:latest
    build: trac
    restart: unless-stopped
    environment:
      - MARIADB_USER=${MARIADB_USER:-changemetoo}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-changemetoo}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-trac}
      - UWSGI_MASTER=true
      - UWSGI_PROCESSES=${UWSGI_PROCESSES:-4}
      - UWSGI_THREADS=${UWSGI_THREADS:-4}
    volumes:
      - ./home:/home/trac
    networks:
      - back
    depends_on:
      - db
    command: uwsgi
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-changeme}
      - MARIADB_USER=${MARIADB_USER:-changemetoo}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-changemetoo}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-trac}
      - MARIADB_AUTO_UPGRADE=true
    volumes:
      - mariadata:/var/lib/mysql
    networks:
      - back

volumes:
  mariadata:

networks:
  front:
  back:
    internal: true
